# Generated by Django 4.1.5 on 2023-01-23 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_email_blog_phone_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 23, 1, 9, 32, 333738, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
