# Generated by Django 4.1.5 on 2023-01-23 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_date_alter_blog_email_alter_blog_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 23, 1, 32, 6, 189482, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
