# Generated by Django 4.1.5 on 2023-01-23 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 23, 4, 43, 58, 656660, tzinfo=datetime.timezone.utc)),
        ),
    ]
