# Generated by Django 4.1.5 on 2023-01-23 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 23, 12, 38, 54, 359842, tzinfo=datetime.timezone.utc)),
        ),
    ]
